#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# in a list format where only the part of the name after the first dash is displayed

command=$(ls)

for i in $command;
do
    echo "$i" | cut -d'-' -f2
done