#!/usr/bin/env bash

cp /etc/hosts ~/hosts.new
sed -i "/.* facebook.com$/d" ~/hosts.new
sed -i "1 s/^/8.8.8.6 facebook.com\n/" ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
