#!/usr/bin/env bash
# Resolves and changes the locahost IP address to 127.0.0.2
sudo cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo '8.8.8.8     facebook.com' >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
